project = "kubernetes-project-313715"
region  = "us-east1"
zone    = "us-east1-c"
topic_name = "production_topic"
#bucketname = "testing-bucket-caio-production"
#bucketname_2 = "testing-bucket-caio-production-2"